export const GET_ALL_MOVIE_REQUEST = "GET_ALL_MOVIE_REQUEST";
export const GET_ALL_MOVIE_SUCCESS = "GET_ALL_MOVIE_SUCCESS";
export const GET_ALL_MOVIE_FAILURE = "GET_ALL_MOVIE_FAILURE";

export const POST_ALL_MOVIE_REQUEST = "POST_ALL_MOVIE_REQUEST";
export const POST_ALL_MOVIE_SUCCESS = "POST_ALL_MOVIE_SUCCESS";
export const POST_ALL_MOVIE_FAILURE = "POST_ALL_MOVIE_FAILURE";

export const DELETE_ALL_MOVIE_REQUEST = "DELETE_ALL_MOVIE_REQUEST";
export const DELETE_ALL_MOVIE_SUCCESS = "DELETE_ALL_MOVIE_SUCCESS";
export const DELETE_ALL_MOVIE_FAILURE = "DELETE_ALL_MOVIE_FAILURE";

export const EDIT_ALL_MOVIE_REQUEST = "EDIT_ALL_MOVIE_REQUEST";
export const EDIT_ALL_MOVIE_SUCCESS = "EDIT_ALL_MOVIE_SUCCESS";
export const EDIT_ALL_MOVIE_FAILURE = "EDIT_ALL_MOVIE_FAILURE";


export const GET_ALL_MOVIEDETAILS_REQUEST = "GET_ALL_MOVIEDETAILS_REQUEST";
export const GET_ALL_MOVIEDETAILS_SUCCESS = "GET_ALL_MOVIEDETAILS_SUCCESS";
export const GET_ALL_MOVIEDETAILS_FAILURE = "GET_ALL_MOVIEDETAILS_FAILURE";

export const GET_ALL_MOVIE_SEARCH_REQUEST = "GET_ALL_MOVIE_SEARCH_REQUEST";
export const GET_ALL_MOVIE_SEARCH_SUCCESS = "GET_ALL_MOVIE_SEARCH_SUCCESS";
export const GET_ALL_MOVIE_SEARCH_FAILURE = "GET_ALL_MOVIE_SEARCH_FAILURE";



